services:
  redis:
    image: redis:8.4.0-alpine
    volumes:
      - ./data/redis:/data
    restart: always

  proxy:
    depends_on:
      - redis
    image: ${PROXY_IMAGE:-ghcr.io/nskondratev/socks5-proxy-server-proxy:latest}
    environment:
      # App settings
      LOG_LEVEL: ${LOG_LEVEL}
      APP_PORT: ${APP_PORT}
      # Redis connection settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # Proxy settings
      REQUIRE_AUTH: ${REQUIRE_AUTH}
      AUTH_CACHE_MAX_SIZE: ${AUTH_CACHE_MAX_SIZE}
      AUTH_CACHE_TTL: ${AUTH_CACHE_TTL}
      PROXY_HANDSHAKE_TIMEOUT: ${PROXY_HANDSHAKE_TIMEOUT:-10s}
      PROXY_IDLE_TIMEOUT: ${PROXY_IDLE_TIMEOUT:-15m}
      REDIS_AUTH_UPDATES_QUEUE_SIZE: ${REDIS_AUTH_UPDATES_QUEUE_SIZE}
      REDIS_USAGE_UPDATES_QUEUE_SIZE: ${REDIS_USAGE_UPDATES_QUEUE_SIZE}
      # Prometheus metrics settings
      METRICS_ENABLED: ${METRICS_ENABLED:-0}
      METRICS_PORT: ${METRICS_PORT:-9100}
      METRICS_AUTH_ENABLED: ${METRICS_AUTH_ENABLED:-0}
      METRICS_AUTH_USERNAME: ${METRICS_AUTH_USERNAME:-}
      METRICS_AUTH_PASSWORD: ${METRICS_AUTH_PASSWORD:-}
      # pprof settings
      PPROF_ENABLED: ${PPROF_ENABLED:-0}
      PPROF_PORT: ${PPROF_PORT:-6060}
      PPROF_AUTH_ENABLED: ${PPROF_AUTH_ENABLED:-0}
      PPROF_AUTH_USERNAME: ${PPROF_AUTH_USERNAME:-}
      PPROF_AUTH_PASSWORD: ${PPROF_AUTH_PASSWORD:-}
      # Telegram bot settings
      TELEGRAM_BOT_ENABLED: ${TELEGRAM_BOT_ENABLED:-1}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_UPDATE_PROCESSING_TIMEOUT: ${TELEGRAM_UPDATE_PROCESSING_TIMEOUT}
      TELEGRAM_USE_WEBHOOKS: ${TELEGRAM_USE_WEBHOOKS}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      TELEGRAM_WEBHOOK_TLS_CERT_PATH: ${TELEGRAM_WEBHOOK_TLS_CERT_PATH}
      TELEGRAM_WEBHOOK_TLS_KEY_PATH: ${TELEGRAM_WEBHOOK_TLS_KEY_PATH}
      BOT_APP_PORT: ${BOT_APP_PORT}
      PUBLIC_URL: ${PUBLIC_URL}
    ports:
      - "${APP_PORT}:8000"
      - "${BOT_APP_PORT}:${BOT_APP_PORT}"
      - "${METRICS_PORT:-9100}:${METRICS_PORT:-9100}"
      - "${PPROF_PORT:-6060}:${PPROF_PORT:-6060}"
    expose:
      - "${APP_PORT}/tcp"
      - "${BOT_APP_PORT}/tcp"
      - "${METRICS_PORT:-9100}/tcp"
      - "${PPROF_PORT:-6060}/tcp"
    restart: always
