name: proxy unit and lint

on:
  pull_request:
    paths:
      - "proxy/**"
      - ".github/workflows/proxy-ci.yml"
  push:
    branches:
      - master
    paths:
      - "proxy/**"
      - ".github/workflows/proxy-ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: proxy/go.mod
          cache-dependency-path: proxy/go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.11.3
          working-directory: proxy
          args: --timeout=5m ./...

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: proxy/go.mod
          cache-dependency-path: proxy/go.sum

      - name: Run unit tests
        run: go test -race ./... -count=1
